// <auto-generated />
using CRUD_API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRUD_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRUD_API.Models.Resident", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resident");

                    b.HasData(
                        new
                        {
                            Id = "qyfgqiyhwfoq1",
                            Name = "Stan Smith",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "qmvqqwrqsds2",
                            Name = "Jack Anderson",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "vdhgqvgj3",
                            Name = "Olga Popova",
                            Sex = "female"
                        },
                        new
                        {
                            Id = "lkqjweiojqiow4",
                            Name = "Erzhena Koroleva",
                            Sex = "female"
                        },
                        new
                        {
                            Id = "hqwuiehquikxhc5",
                            Name = "German Titov",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "guyqwhoij6",
                            Name = "Dmitry Vegas",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "kjlqwoijeo7",
                            Name = "Solomon Shlemovich",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "lkkpokqw8",
                            Name = "Alex Whitedrinker",
                            Sex = "female"
                        },
                        new
                        {
                            Id = "acmwojeiwqe9",
                            Name = "Anna Titova",
                            Sex = "female"
                        },
                        new
                        {
                            Id = "qjIdwojqiowj10",
                            Name = "Elmo Kennedy",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "cnoqjpIdjkqpo11",
                            Name = "Sascha Braemer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "ajkvdnLdj22po11",
                            Name = "Pishkun Vladislav",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "djkqpo11cnoqjpI",
                            Name = "Jessica Braemer",
                            Sex = "female"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
